#!/usr/bin/bash
i3lock -n \
    --insidecolor=0c0c0cff --ringcolor=ffffffff --line-uses-inside \
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff \
    --radius=15 --veriftext="" --wrongtext="" --color=0c0c0c
